#! /bin/sh
#startups
# picom &
# bash ~/.fehbg &
polybar &
# copyq &
# redshift &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap          13
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config focused_border_color "#5390D9"
bspc config normal_border_color "#323248"
bspc config presel_feedback_color "#FF2945"

bspc config urgent_border_color "#D3304B"
bspc config focused_locked_border_color "#D3304B"
bspc config normal_sticky_border_color "#D3304B"
bspc config normal_locked_border_color "#D3304B"
bspc config focused_sticky_border_color "#D3304B"

#bspc config top_padding                   0
#bspc config bottom_padding                0
#bspc config left_padding                  0
#bspc config right_padding                 0
#bspc config single_monocle                false
#bspc config click_to_focus                true
#bspc config focus_by_distance             true
#bspc config focus_follows_pointer         true
#bspc config history_aware_focus           true
#bspc config remove_disabled_monitors      true
#bspc config merge_overlapping_monitors    true
#bspc config pointer_modifier mod4
#bspc config pointer_action1 move
#bspc config pointer_action2 resize_side
#bspc config pointer_action3 resize_corner


bspc rule -a Zathura desktop='^2' state=fullscreen follow=on
bspc rule -a vlc desktop='^3' follow=on focus=on
bspc rule -a Google-chrome desktop='^4' follow=on focus=on
bspc rule -a mplayer2 state=floating
bspc rule -a copyq state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
